name: Check label Rules Cumulus

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Pull image
        env:
          IMAGE: paritytech/ruled_labels:0.4.0
        run: docker pull $IMAGE

  check-label-rules:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        repo: [cumulus, polkadot]

    steps:
      - name: Check label Rules for ${{ matrix.repo }}
        env:
          IMAGE: paritytech/ruled_labels:0.4.0
          MOUNT: /work
          RULES_PATH: ruled_labels
        run: |
          docker run --rm -i -v $PWD/${RULES_PATH}/:$MOUNT $IMAGE test -s ${MOUNT}/specs_${{ matrix.repo }}.yaml ${MOUNT}/tests_${{ matrix.repo }}.yaml
